project:
  type: website
  output-dir: ../docs

website:
  title: "Medicaid Final Project"
  navbar:
    left:
      - file: index.qmd
        text: "Write-Up"
        
  sidebar: 
    - title: "Write-Up"
      contents: 
        - text: "Introduction/Overview"
          file: index.qmd
        - text: "Program Theory and Implementation"
          file: src/writeup/theory-and-implementation.qmd
        - text: "Outcome and Causation"
          file: src/writeup/outcome-and-causation.qmd
        - text: "Data and Methods"
          file: src/writeup/data-and-methods.qmd
        - text: "Synthetic Analysis"
          file: src/syntheticData/synthetic-analysis.qmd
        - text: "Synthetic Analysis (with code)"
          file: src/syntheticData/synthetic-analysis-with-code.qmd
        - text: "Conclusion"
          file: src/writeup/conclusion.qmd

        
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

