---
title: "Overview"
editor: visual
---

# 1: Introduction

Healthcare costs for United States citizens have been increasing for several decades, and the need for affordable healthcare has never been higher. In 2010 the Obama Administration initiated the Affordable Care Act (ACA) as their solution for high healthcare costs, and the policy went into full effect in 2014. This study uses a difference-an-difference model to analyze the policy's effect on healthcare access between enrolled and non-enrolled states. Policymakers can use the results of this study to assess the benefits and costs of public healthcare programs. For this reason, it is essential that the results are as unbiased as possible. To prevent p-hacking, this analysis is built around synthetic data created in the r programming language. Once the actual data is acquired, it can be piped through the same model.

# 2: Program background and purpose

In the years leading to Medicaid, the rising cost of health insurance was a hot topic, and the need for government assistance was increasing. The United States population was proliferating, and many were from lower-class families. Between 1950 and 1963, hospital costs increased 6.7 percent a year, well above the rate of change in the cost of living. The federal government tried several half-measure programs, such as the Kerr-Mills act, which fell short of its intentions to lower costs for the increasingly elderly populous. Disapproval for this Act spread throughout advocacy groups in the United States, and many states were putting off enrollment.

In 1965, Title XIX was signed by Lyndon B. Johnson, creating Medicaid, a comprehensive health coverage plan for low-income families. Kerr Mills uses a partnership between state and federal funds like its predecessor. State participation was not mandatory but greatly incentivized. To qualify for Medicaid enrollment, citizens had to fall into two categories. One, they needed to be below the poverty line (by how much varied across states), and two, they needed to have a disability. Examples of qualifying disabilities are having a breast cancer diagnosis, blindness, physical disabilities, or becoming pregnant.

In 2010, the Obama Administration signed the Affordable Care Act (ACA) Medicaid Expansion into existence. The Act lowered the qualification categories from two to one. Enrollees only needed incomes up to 138% of the poverty line to receive Medicaid coverage. Initially, 35 states enrolled as well as Washington D.C. Additionally, the ACA provides premium tax credits for private health insurance, eliminates preexisting condition exclusion, and allows young adults to stay on their parent's health insurance until age 26.
